package org.acme.travels

import org.acme.travels.VisaApplication;
import org.acme.travels.VisaResolution;

rule "Visit Australia with e-visa up to 90 days" ruleflow-group "visa-approvals"

when
    $application: VisaApplication(duration <= 90, country == "Australia")
    $resolution : VisaResolution()
then
    $resolution.setApproved(true);
    $resolution.setReason("Automatic visa approval");
end

rule "Visit US with e-visa up to 15 days" ruleflow-group "visa-approvals"

when
    $application: VisaApplication(duration <= 15, country == "US")
    $resolution : VisaResolution()
then
    $resolution.setApproved(true);
    $resolution.setReason("Automatic visa approval");
end